# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-07 03:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ttio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='question',
            field=models.TextField(),
        ),
    ]
