# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-08 04:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ttio', '0002_auto_20161207_0323'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='failures',
            field=models.IntegerField(default=1),
        ),
    ]
